name: .NET Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  welcome-message:
    name: Welcome Message
    runs-on: ubuntu-latest
    steps:
      - name: Print Welcome Message
        run: echo "Welcome to the .NET Pipeline"

  build-test-publish:
    name: Build, Test, and Publish
    runs-on: ubuntu-latest
    needs: welcome-message
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x' 

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish

